dist: xenial
sudo: required
language: node_js
node_js:
- lts/*
install:
- yarn
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- hugo version
- yarn run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_8545b8dfd984_key -iv $encrypted_8545b8dfd984_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - NODE_ENV=production
  - PRODUCTION=true
  - HUGO_RELEASE=0.54.0
  - secure: bVeVmwo8v97DGz7pJVFv3TvR/gUe4o0YAAgJ+84MzvM1MRnHEJPW65TZfD23i6p0PjkoeniSODSejSysBlitdMLePGyRj+cSlNKpiZO4mfVX/TCw99dIyDUWnMYLaVr/J/wVDgWdyBZ6UkyH8zsIgS7g8gedUZ4YH5rx7wEzoQGyueHVUfuwv1tESzQxEaEoFkQUBiD8sFk5+BuY4dQZj7V7ttAoAuaMrQUI5OH2eoKX27abcyo6lAtfBJXi5Ko4DL35eO8rGt/27efDzUXn+AGBieJK8ihntfaVaIXzxIqRjb0kPm7QI9d80vRYPs9WiIK01N45uwV/mWWHFcUTrBogQtr25mOUsk/Dzila0RzevDScdluWX30Z2BH8puKR+WUhMTUi2AN252K95hfv28VVQdgJf02nwT5xMWlnBvcG0rjvugOl832g+qvlOl8dgpTdvUG/7HkKeb2bQ/WdOa1P9bPQNNMCjsVU5rwZHJWIp+uoMLxhWpYUQnvFSVw2XPORBOQ/OfkcpBqGD5TdCNQYVK69unYT39POUgxOfZS0sZw+FGtyanG3z2QaOhC9JgX7sqVSMMq1xQ9Tsu+8nTEZ2w5idLA7HypMelEpTCP2mhsmUklE1JLPJKqv5adZaJ5Ht5MSgS5EX8/4p/T3QP3dyGzfyiTP+TaguBR5Tzs=
  - secure: nJsNifhSTaP6P2AcjBEEUCS9OyVYmo9B2Nl+WKKnaq+L+QY7QRLllJfB60Tue3A2PellxuA/xSsgjj1U8sxPlPImyPexu32s7WQFTwSl+IT3xP1r4r00Mq2yYxXYee8blGF/WHbE5+iSjsdo1O74uzOkePObcatnbwx37fiYRZq2r5gSb36UltqZj4vJLOJi9Ex4Pv4TYaS8l/i9+92bh19VVrscbHsnsqd8N3Mi7IOOqZUNHhs0Omifjiwp0U2y0JbP8GsTYcnf5pgFEjSdqm1Fibd5gun6pt8jXzEP54LhagT+yLnDjnuF/LL8KY8vkXGArG73IL19KRDuIJtJAdkQ6FYrKrfRr2tCcgNMSzjzjVFY+EhtIDjA7Ad86/O6y0vaufKYfN6VA3W95y8DaoZRRPvgFgKuSXnR8LHm6w8YVa+M+/vA2C0+/uFoLDv4r1W4Fnxpedu6BHn3mDIRyGZt6zKyQe69lLC6FNocr09D2oIpXmbJA4RAp/EyrSkqt4DfzUiAi+MJoWecWtp8ddA78dZsPU0cElhIZzkhhwLQvnxC3t+Ou0UqTK1CnUeLFqdUgcRE48130Vd0frd6IbPtNp0oO5ZRbPtHoOaaBIb3hBoP+kSSeKFoovcM48B1qbud7Fzku8RXpAh32RHKsz+R9IqUJt3RMzmMm4oEHow=
  - secure: PJQGsqP7PqP+egxJGn5ZpsjLOWpnI2fkQNm/qZ0DcQY1boDY/a2AZG/vIkLKS0n/6k7vyUJZf3I+Qnd0fTCnRhDD5jUzeZyGUeBNB/5MvgQv1ms30wLxu2Tbbvh8Mwg7tH8xcpWLvc0wIYbSAUagJW/mvES6GkkyYvHnRNCtIdbR9T41p+REFBg9KT4lYq7ULAV0J9w8TuwDzvckyPAL7fnTTFwVYLT3oYt5WpToiAWW/7EDo1A9ciWCYP5P8uljWLHkP0c9Z9dSYwYEW+UGCYHKdJCMBlYx6Xb8bsUQ+DBjqOMYlperGmmfCP391WFF/dpabPNIt0BR3AgBrghejkfEI8Ob5472Nv+o22DgUw47aQ8+ixYs6NZKTQ2Lsa1JjwpRuwYlugBzc6btBX/fFeIR9W0KY7LW/Aq8R68yVml/cqRVjVzLVzzmnk8a7hqE4ZYfV6RxH+K2RIWZ5ec2ZVmB//bDQMQhGQWgGHp9ibDVcsbgxC14f3Ti25BLbuRY0r0SZyjCJvyEjdYCdOzGkkia0PKko91aRYYI9LkZ6OJOAYJKheyuS0/quWDGndWf1m2spO2oC99nAwkALhqUQzXeUL2WZC/ViWLyHsS7VGeoVr8K0EOe3+U0hwaPJtdUBBnOngB6ljoyvVjCtHn6KbDycewIRn4s+Is29ntV8Io=
  - secure: FDlMDiUbGkBDxXXwcC0OrbwE3z5N5p8Nja1rx48z3rjEtgd34VJrskayLebCpyRDEgRgKjYJvzxvX5w44tSJ5JXoFZCTgUakfwPOFHkxWQfgNBYVzvUdtwx5gHKhz+va5SpnX5X5pC2DRtjsscD92ctyrQZTpNP1uPXpdl7leqrvOGY6Lwo28Sp/RD90Wz/KXG5Pk5lFFebjh8eOkkHdOnijUv+wwmr21t7STW9Qrn8YjgO45ooH8dQ6k9H1ihgp19QsS2cU6aOeFM1Y/ebNscnBTp919hL+Ez+GRO7EDXKA6s58JAJ8sTZdFMKXbVCxqhKDh0qm/ggqfMbeSUDtvXP2mya0ruI40UhSZkoT6AIeg3S5v2EzcwiNSIdpNFGEVrHnPWzmu0M1QlvrUJjNkSDSWX70/blOnH1aRq+SeVKqsnceAtxJoQGvUINe8VoQlJbFbHQt34GaMFfDXoyKSoJzVGaclM5HvhiRrGpU3WUR4kkf8AkhMn+1M3NyyzXVpiKMf9Y4ZWuiUGJCVIZOPntt647L82PZNT7XJdYQ3GsyUe7uTBceVqqpd8d1nos9AdSRXiG4187aN9OzedKnK0eH7p3AenpRyvEiR1o6PUx6jcBT0uP5yg6ofo3TP0GpURIttJq/d8mArO/y9vpEg8slbuqhzi27jdmg2vQPBw4=
