baseURL: "https://wonderful-swanson-f65e38.netlify.com"
defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
buildFuture: true
outputs:
  home:
    - HTML
    - JSON
  page:
    - HTML
    - JSON
  section:
    - HTML
    - JSON

# disableKinds:
#   - "section"
#   - "taxonomy"
#   - "taxonomyTerm"
#   - "RSS"
#   - "sitemap"
footnoteReturnLinkContents: "↩"
googleAnalytics: ""
languageCode: "pt-br"
enableMissingTranslationPlaceholders: true
defaultContentLanguage: "pt-br"
menu:
  header:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 1
  - identifier: "idea"
    name: "IDeA"
    url: "/idea"
    weight: 2
  - identifier: "Project"
    name: "Projeto"
    url: "/projeto"
    weight: 3
  - identifier: "pesquisas"
    name: "Pesquisas"
    url: "/pesquisas"
    weight: 4
  - identifier: "inspirese"
    name: "Inspire-se"
    url: "/inspirese"
    weight: 5
  - identifier: "novidades"
    name: "Novidades"
    url: "/novidades"
    weight: 6
  - identifier: "parceiros"
    name: "Parceiros"
    url: "/parceiros"
    weight: 7
  - identifier: "contato"
    name: "Contato"
    url: "/#contato"
    weight: 8
metaDataFormat: "yaml"
title: "IDeA"
params:
  mailchimpNewsletterFormAction: ""
  siteDescription: ""
  tagline: ""
  twitterUsername: "appcivico"
  shareImages:
    default: "images/sharing/Compartilhamento_blockchain.jpg"
    twitter: "images/sharing/Compartilhamento_twitter.jpg"
    facebook: "images/sharing/Compartilhamento_blockchain.jpg"
  socialNetworksLinks:
    twitter: "https://twitter.com/appcivico"
    # medium: "https://medium.com/app-civico"
    facebook: "https://www.facebook.com/AppCivicoCSB"
    # github: "https://github.com/AppCivico"
    youtube: "https://www.youtube.com/channel/UCIuAzzWMogJV0r-mvFmjNNQ"
taxonomies:
  tag: tags
  pais: paises
  area: areas
