backend:
  name: github
  repo: AppCivico/tide-www # Path to your Github repository
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://portalidea.org.br/callback
  accept_roles:
    - admin
    - editor
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  -
    label: "Homepage"
    name: "home"
    folder: "content/"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h1"
      -
        label: "Texto do Botão"
        name: "callToActionText"
        widget: "string"
        required: false
      -
        label: "Url do Botão"
        name: "callToActionUrl"
        widget: "string"
        required: false
      -
        label: "Data"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "Rascunho"
        name: "draft"
        widget: "boolean"
        default: true
      -
        label: "Conteúdo"
        name: "body"
        widget: "markdown"
  -
    label: "Depoimentos"
    name: "testimonials"
    folder: "content/depoimentos"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h1"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Data"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "Rascunho"
        name: "draft"
        widget: "boolean"
        default: true
      -
        label: "Nome"
        name: "name"
        widget: "string"
      -
        label: "Imagem (432 X 432)"
        name: "Image"
        widget: "image"
      -
        label: "Video"
        name: "video"
        widget: "string"
      -
        label: "Texto alternativo da imagem"
        name: "alt"
        widget: "string"
      -
        label: "Ordem"
        name: "weight"
        widget: "number"
      -
        label: "type"
        name: "type"
        widget: "hidden"
        default: "item"
      -
        label: "role"
        name: "role"
        widget: "hidden"
        default: "testimonials"
      -
        label: "Conteúdo"
        name: "body"
        widget: "markdown"
  -
    label: "Novidades"
    name: "novidades"
    folder: "content/novidades"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h3"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Data"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "Tags"
        name: "tags"
        widget: "list"
        default: ["news"]
      -
        label: "Imagem (600x500)"
        name: "image"
        widget: "image"
        required: false
      -
        label: "Imagem (1000x600)"
        name: "image_big"
        widget: "image"
        required: false
      -
        label: "Texto alternativo da imagem"
        name: "alt"
        widget: "string"
        required: false
      -
        label: "Descrição curta (resumo)"
        name: "short_description"
        widget: "string"
      -
        label: "Conteúdo"
        name: "body"
        widget: "markdown"
  -
    label: "Inspire-se"
    name: "inspire-se"
    folder: "content/inspirese"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h3"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Data"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "Países"
        name: "paises"
        widget: "list"
      -
        label: "Imagem (600x500)"
        name: "image"
        widget: "image"
        required: false
      -
        label: "Imagem (1000x600)"
        name: "image_big"
        widget: "image"
        required: false
      -
        label: "Texto alternativo da imagem"
        name: "alt"
        widget: "string"
      -
        label: "Arquivo"
        name: "file"
        widget: "file"
        allow_multiple: false
      -
        label: "Autor"
        name: "author"
        widget: "string"
      -
        label: "Descrição curta"
        name: "short_description"
        widget: "string"
      -
        label: "Conteúdo"
        name: "body"
        widget: "markdown"
  -
    label: "Pesquisas"
    name: "pesquisas"
    folder: "content/pesquisas"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h3"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Data"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "Áreas"
        name: "areas"
        widget: "list"
      -
        label: "Arquivo"
        name: "file"
        widget: "file"
        allow_multiple: false
        required: false
      -
        label: "Descrição curta"
        name: "short_description"
        widget: "string"
      -
        label: "Conteúdo"
        name: "body"
        widget: "markdown"
      -
        label: "Custom link"
        name: "custom_link"
        widget: "string"
        default: "/desigualdade-escolares"
        required: false
  -
    label: "Projeto"
    name: "projeto"
    folder: "content/projeto"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h3"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Conteúdo"
        name: "body"
        widget: "markdown"
      -
        label: "Arquivo"
        name: "file"
        widget: "file"
        allow_multiple: false
  -
    label: "Pobreza desigualdade e educação"
    name: "desigualdades escolares"
    folder: "content/desigualdades-escolares"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h3"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Data"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "Ordem"
        name: "weight"
        widget: "number"
      -
        label: "Custom link"
        name: "custom_link"
        widget: "hidden"
        default: "/desigualdade-escolares"
      -
        label: "Texto em português"
        name: "texto_portugues"
        widget: "markdown"
      -
        label: "Texto em inglês"
        name: "texto_ingles"
        widget: "markdown"
      -
        label: "Bibliografia principal"
        name: "bibliografia_principal"
        widget: "markdown"
      -
        label: "Bibliografia secundária"
        name: "bibliografia_secundaria"
        widget: "markdown"
      -
        label: "Bibliografia principal PDF"
        name: "main_bibliography_pdf"
        widget: "file"
        allow_multiple: false
        required: false
      -
        label: "Bibliografia secundária PDF"
        name: "secondary_bibliography_pdf"
        widget: "file"
        allow_multiple: false
        required: false
      -
        label: "Arquivo"
        name: "file"
        widget: "file"
        allow_multiple: false
        required: false
      -
        label: "Descrição curta"
        name: "short_description"
        widget: "string"
        required: false
  -
    label: "Projeto"
    name: "projeto"
    folder: "content/projeto"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h3"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Conteúdo"
        name: "body"
        widget: "markdown"
      -
        label: "Arquivo"
        name: "file"
        widget: "file"
        allow_multiple: false

  -
    label: "Parceiros"
    name: "parceiros"
    folder: "content/parceiros"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h3"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Conteúdo"
        name: "body"
        widget: "markdown"
