backend:
  name: git-gateway
  repo: eokoe__frontend/tide
  branch: cms
  accept_roles:
    - admin
    - editor
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  -
    label: "Index"
    name: "index"
    folder: "content/"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      -
        label: "Title"
        name: "title"
        widget: "string"
        tagname: "h1"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
      -
        label: "Body"
        name: "body"
        widget: "markdown"

